### ISSUE TITLE
Missions Ghost Hunting - Trick or Treat -> no boarding convo pop-up

### ISSUE THREAD

**Issue by zen-moto** [MidnightPlugins/Lost-in-Midnight#1]
Interacting with the npc ships, none of them respond to boarding action, beyond the docking animation. Code shows there should be a convo trigger but not happenning.

plugin version: Lost-in-Midnight-0.9.14.1
ES version: endless-sky-win64-0.9.14

**Comment by MidnightPlugins** [comment]
Looks like this is caused by the reputation for government Derelict (Killable) havinga non-negative value. Will update in a bit.

**Comment by MidnightPlugins** [comment]
plugin version: Lost-in-Midnight-0.9.14.2 is released.

Files updated:

https://github.com/MidnightPlugins/Lost-in-Midnight/blob/main/data/Governments%20Misc.txt

https://github.com/MidnightPlugins/Lost-in-Midnight/blob/main/data/Missions%20Ghost%20%20Hunting.txt
