### ISSUE TITLE
hidden systems

### ISSUE THREAD

**Issue by mrdibb40** [MidnightPlugins/Lost-in-Midnight#13]
less of an issue possibly than I just can't find it.  How do you access the hidden systems?  Particularly I did the jobs to reassemble the Exodus and the last ship is in the Archipelago system which I can find anywhere.  I've explored all of the map.  Looking through the plugin files I found the midnight map file with the list of hidden systems and none of them have been exposed so I feel that I am missing something in order to access these systems.   I'm currently using version 0.9.14.15.27

amazing set of plugins by the way.  really breathes new life into the game.

**Comment by MidnightPlugins** [comment]
Thank you! Most hidden systems are revealed through the Cartography mission chain. There are two parts to starting the chain:

PART 1:
1-need first contact with Quarg

2-either dominate all vanilla pirate worlds or have positive rep with pirates

3-visit pirate spaceports until you're approached by a Quarg hitchhiker

PART 2:
1-need first contact with Coalition

2-become famous helping Foster uncover Sheragi ruins

3-hang out near Graffias until invited to investigate archaeology on Poisonwood

**Comment by mrdibb40** [comment]
> Thank you! Most hidden systems are revealed through the Cartography mission chain. There are two parts to starting the chain:
> 
> PART 1: 1-need first contact with Quarg
> 
> 2-either dominate all vanilla pirate worlds or have positive rep with pirates
> 
> 3-visit pirate spaceports until you're approached by a Quarg hitchhiker
> 
> PART 2: 1-need first contact with Coalition
> 
> 2-become famous helping Foster uncover Sheragi ruins
> 
> 3-hang out near Graffias until invited to investigate archaeology on Poisonwood

haven't dominated all the pirate systems this game.  that's it.  thanks very much!
