### ISSUE TITLE
Weaponized Subsidurial mission description missing payment amount

### ISSUE THREAD

**Issue by Morcleon** [MidnightPlugins/Lost-in-Midnight#14]
In /data/drak midnight/Lifeforms Indigenous.txt, the "Weaponized Subsidurial Bounty" is missing angle brackets around "Payment is <payment>." In-game, it doesn't show the actual numerical value for the payment.

**Comment by MidnightPlugins** [comment]
thanks, will look into it

**Comment by MidnightPlugins** [comment]
Found it. File updated, will include in next release.

Thank you!
