### ISSUE TITLE
<waypoints> in dialog but mission "Pot-o'-honey" doesn't have a waypoint

### ISSUE THREAD

**Issue by trunksbomb** [MidnightPlugins/Lost-in-Midnight#16]
https://github.com/MidnightPlugins/Lost-in-Midnight/blob/e2f0831f747639d09065a534d28eda96df01c43a/data/human%20midnight/Missions%20Double%20Cross.txt#L1178

The text `<waypoints>` actually shows up in game and doesn't get replaced because the mission doesn't actually have a waypoint. Based on the rest of the mission, I reckon that's supposed to literally be the system "Waypoint" since you have a fleet spawn in Waypoint.

**Comment by MidnightPlugins** [comment]
Thanks, the mission was missing a waypoint for "Waypoint"! Updated with the missing waypoint.
