### ISSUE TITLE
Bug in Hunting Beelzebub

### ISSUE THREAD

**Issue by animoose** [MidnightPlugins/Lost-in-Midnight#17]
https://github.com/MidnightPlugins/Lost-in-Midnight/blob/e2f0831f747639d09065a534d28eda96df01c43a/data/remnant%20midnight/Missions%20Hunting%20Beelzebub.txt#L21

I think this should say 
attributes "south"

**Comment by animoose** [comment]
I checked this further and it ought to work with "south pirate". However what I found was that when I changed the line I could get the mission to trigger immediately while before I changed the line it never triggered, many visits to planet with the "south pirate" attribute.

**Comment by MidnightPlugins** [comment]
Thanks. It actually is intended to have attributes "south pirate". This allows for the mission to trigger at former pirate worlds in the south as well as southern pirate worlds with the "Pirate" government.

The mission had a 30% - "ignored" chance to trigger, so you could have just had unfortunate RNG.

To help address this, increased the initial offer to 70% while keeping subsequent deferred offers at 30% - "ignored paris".
