### ISSUE TITLE
Mission "Midnight Earth Retirement Inheritance"

### ISSUE THREAD

**Issue by Durzai** [MidnightPlugins/Lost-in-Midnight#21]
This mission is missing the date mentioned in the line "It can't be held any later than <Blank>." Screenshot is attached for reference.

![MissingDate1](https://github.com/MidnightPlugins/Lost-in-Midnight/assets/105894839/7b4eb5d5-0500-4b1f-a624-becad154d069)

**Comment by MidnightPlugins** [comment]
Thanks. A fix has been uploaded to the repository and will be included in the next release!
