### ISSUE TITLE
Mission "Limit Breaker Syndicate Patrol"

### ISSUE THREAD

**Issue by Durzai** [MidnightPlugins/Lost-in-Midnight#22]
Typo during Mission "Limit Breaker Syndicate Patrol", "runors" instead of "rumors", screenshot attached below for reference.

![Typo8](https://github.com/MidnightPlugins/Lost-in-Midnight/assets/105894839/59322d8a-2edb-486e-a828-6037d5a68fa6)

**Comment by MidnightPlugins** [comment]
Thanks. A fix has been uploaded to the repository and will be included in the next release!
