### ISSUE TITLE
Mission "Oathbreaker Supply Run"

### ISSUE THREAD

**Issue by Durzai** [MidnightPlugins/Lost-in-Midnight#23]
This mission uses a masculine pronoun when referring to F/L, screenshot attached below. Dialogue is "Or does the hero of the war intend to cower inside his ship indefinitely?"

![Pronoun1](https://github.com/MidnightPlugins/Lost-in-Midnight/assets/105894839/4db50896-d74e-4b01-b903-fc6eda12e51a)

**Comment by MidnightPlugins** [comment]
Thanks. A fix has been uploaded to the repository and will be included in the next release!

_"Or does the hero of the war intend to cower inside that miserable tin can indefinitely?"_
