### ISSUE TITLE
Mission "Angry Squirrels: Fragmentation Grenade Deal"

### ISSUE THREAD

**Issue by Durzai** [MidnightPlugins/Lost-in-Midnight#24]
When completing this mission of delivering 100 Frag Grenades a picture of Enforcer Confrontation Gear is shown instead of Fragmentation Grenades. See attached screenshot.

![WrongPicture1](https://github.com/MidnightPlugins/Lost-in-Midnight/assets/105894839/f3fb74ab-3d24-4b2a-83ac-ec33a6d8dc1a)

**Comment by MidnightPlugins** [comment]
Thanks. A fix has been uploaded to the repository and should be included in the next release!
