### ISSUE TITLE
Quantum Key Blade Missions

### ISSUE THREAD

**Issue by Durzai** [MidnightPlugins/Lost-in-Midnight#25]
There are several missions that require you to land on Hai-Home during this mission chain, and if Hai-Home is restricted to you when you receive these missions you can not progress with them. Hai-Home being restricted can be caused by a multitude of actions, such as Unfettered weapons deals before this mission chain is unlocked, thereby making it extremely difficult, if not impossible to complete without save editing.

I was able to continue this mission chain by editing my save file and adding the "clearance" qualifier underneath "destination Hai-Home" whenever I was sent back to Hai-Home, which is the same method used during the Hai Reveal missions to allow you to land on the planet when you may otherwise have reputation restrictions.

Screenshots are attached to give an example of what I did to get things working, there might be other solutions, but this seemed to be the simplest and is in line with other Endless Sky content in the main branch.

![QuantumKeyblade1](https://github.com/MidnightPlugins/Lost-in-Midnight/assets/105894839/99409b5f-ef0a-4921-aea3-ddd7044c6976)

![QuantumKeyblade2](https://github.com/MidnightPlugins/Lost-in-Midnight/assets/105894839/01ea3831-6219-418e-9ec7-9bc6b5dfcb24)

**Comment by MidnightPlugins** [comment]
This one is going to be a little more involved than the others. I've decided to make having enough rep to land on Hai-Home a requirement for the earlier mission when Sayari asks the player to go there.

I'm probably also going change the conversation to branch off in an alternate direction if the player returns the blade while having negative reputation.

Thanks for the error reports! They'll help me make this a better plugin.
