### ISSUE TITLE
Mission "Wanderer Ringworld Debris 1"

### ISSUE THREAD

**Issue by Durzai** [MidnightPlugins/Lost-in-Midnight#26]
During this mission, if an ion storm hits the system while you are waiting for the ship "Timer Ship" "Timer", the mission will instantly fail. I had to revert to my last save multiple times before I managed to get it to run properly without an ion storm rolling into the system.

**Comment by MidnightPlugins** [comment]
Thanks. Decided to remove the Timer Ship and just say you find it "after some time". Fix uploaded to the repository and will be included in next release!
