### ISSUE TITLE
What are barracks supposed to do?

### ISSUE THREAD

**Issue by junetried** [MidnightPlugins/Lost-in-Midnight#27]
The [barracks](https://github.com/MidnightPlugins/Lost-in-Midnight/blob/1b093e758bf6b81c5af64d170d2243d50768213e/data/human%20midnight/Outfits%20Human.txt#L21) outfit doesn't seem to have any point. Increasing the required crew can only be a bad thing, and it doesn't actually increase bunk count. Is it intended to make escorts harder to board? If so, it probably shouldn't take outfit space or have mass, because it would be expensive enough to use without having to sacrifice more useful outfits.

**Comment by MidnightPlugins** [comment]
It is intended to make enemy computer controlled ships harder for the player to board.
