### ISSUE TITLE
Duplicate Image - Model Turret

### ISSUE THREAD

**Issue by Durzai** [MidnightPlugins/Lost-in-Midnight#29]
As far as I can tell, this did not cause any error in cloning the repository, but there are two Model Turret .pngs in the hardpoint images folder, and it throws this warning when cloning the repository to your local plugins folder.

![LIM Warning](https://github.com/MidnightPlugins/Lost-in-Midnight/assets/105894839/646ba932-26b2-4836-a95e-401bbe168e7c)

**Comment by MidnightPlugins** [comment]
Thanks, I forgot to delete the one with capitalized letters.
