### ISSUE TITLE
Idea: add a spellcheck

### ISSUE THREAD

**Issue by TheGiraffe3** [MidnightPlugins/Lost-in-Midnight#40]
Do you have any interest in running a spellcheck on this repository to tell you when there are misspelled words?

I have one I could PR to you, but I don't really want to fix the one hundred and fifty-five lines of errors it throws.

**Comment by MidnightPlugins** [comment]
No thanks. Will fix manually as I find them or they're pointed out to me.

**Comment by TheGiraffe3** [comment]
https://github.com/TheGiraffe3/Lost-in-Midnight/actions/runs/11080742944/job/30791602911

Here are all the ones a spellcheck could find.
