### ISSUE TITLE
Buying/salvaging ships

### ISSUE THREAD

**Issue by Bowenarrow777** [MidnightPlugins/Lost-in-Midnight#7]
I will complete the required items to gain the new vessel, it just doesn't put it as a part of my fleet

**Comment by MidnightPlugins** [comment]
I'm sorry, but you'll need to clarify the issue. Which vessel?

**Comment by MidnightPlugins** [comment]
Are you on version 0.9.13 or later? Those missions rely on the "give ship" command which doesn't exist in 0.9.12.

**Comment by MidnightPlugins** [comment]
Sorry for the late response,

This buying/salvaging ships error may be caused by using an older version of Endless Sky. 0.9.12 version doesn't support the "give ship" mission command. Updating to the 0.9.13 beta or 0.9.14 stable should fix it.
________________________________

**Comment by MidnightPlugins** [comment]
Now that Steam has access to 0.9.14, this should no longer be an issue for most players.
